name: Continuous integration and testing
on: push

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check formatting with black
        run: uvx black -l 100 --check .
      - name: Check linting
        run: uvx ruff check
      - name: Test with python ${{ matrix.python-version }}
        run: uv run --all-groups --frozen pytest
